### ISSUE TITLE
Package compatible with v8 listed in v7 packages!

### ISSUE THREAD

**Issue by Abuabdelah** [umbraco/Umbraco.Packages#46]
uGardian [v8 ](https://our.umbraco.com/packages/backoffice-extensions/ugardian/)package listed in v7! it should display only one.

![image](https://user-images.githubusercontent.com/52907282/64855353-fee10200-d61f-11e9-9cc4-909f6bc022f9.png)
 
![image](https://user-images.githubusercontent.com/52907282/64855436-259f3880-d620-11e9-8a91-78c6d39b4ad5.png)

**Comment by dawoe** [comment]
Hi @Abuabdelah 

When I view your package on our it says minimum version is 7 

![image](https://user-images.githubusercontent.com/1193822/74945063-59646280-53f7-11ea-9d31-021ef98fdf7c.png)

This is caused because in your package.xml file you specified 7.0.0 as the mininal version.

When a package is uploaded on our the package xml file get's parsed and this minimal version is stored within the package information. 

See https://github.com/umbraco/OurUmbraco/blob/3c68537bf1838447f1a575a1e746ff1243d646c9/OurUmbraco/Wiki/Extensions/MediaExtensions.cs#L37

This is causing your package to be visible in the listing for v7 packages.

Dave

**Comment by DanDiplo** [comment]
It seems to me like the version filter is just completely not working. If I filter for v8 packages - https://our.umbraco.com/packages/?version=8 - the majority of them are not v8 packages at all.

![image](https://user-images.githubusercontent.com/6676168/78667397-c1500900-78d0-11ea-8235-4aaaa1181a71.png)

**Comment by KevinJump** [comment]
Yeah i noticed this too the other day - We didn't change the filtering code when we changed the layout but there is a pending PR which unifies the search on the site with the one used within the Umbraco Backoffice (https://github.com/umbraco/OurUmbraco/issues/554) 

I am hopeful this will fix some of this, but it will also allow us to actually work on "one true search" for package and filter this stuff out.

**Comment by KevinJump** [comment]
Hi 

The PR has been merged and applied now, so it looks like the list is a lot better - in terms of listing only the right version with each.

![image](https://user-images.githubusercontent.com/431231/79873445-07cc5a00-83df-11ea-8f64-a0a6cf9e8acd.png)

I've spotted one package (uIntra) that seems to be in the v8 list, when its not 
![image](https://user-images.githubusercontent.com/431231/79873519-1fa3de00-83df-11ea-9be2-594b580496b0.png)

but that's also true in the v8 back office 

![image](https://user-images.githubusercontent.com/431231/79873562-31858100-83df-11ea-9456-702c110ed849.png)

 so at least we are now consistent 😉 

but in all seriousness, now the two searches are merged into one, we can start to squash these remaining few issues. (and added bonus there is now a order by downloads option - https://our.umbraco.com/packages/?orderBy=downloads)

**Comment by DanDiplo** [comment]
Had a quick look and it seems to be working as expected. Great work, Kev! BTW, aren't there a lot of U4 packages still knocking around 😄

**Comment by KevinJump** [comment]
Closing this .. because it looks like it is still working :)
