### ISSUE TITLE
Request a Cloud review

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco.Packages#53]
When creating a package node on Our we should have some way for a user to flag their package as Cloud compatible.

This should then be available for the package team to test on Cloud and it could then get the "Works on Cloud" flag.

Related to https://github.com/umbraco/Umbraco.Packages/issues/50

**Comment by LottePitcher** [comment]
So somewhere in the packages area we could add the ability for a package developer to inform the HQ that their package is cloud compatible.  In the first instance it can send an email to keep it simple to package team for handle.

**Comment by ronaldbarendse** [comment]
We dropped the 'Works on Cloud' flag on the Marketplace, because most (if not all) packages will simply work now we're using modern .NET (since v9) and a more standardized hosting platform (Azure Web Apps). And since this was an opt-in flag, it also looked like a lot of packages weren't compatible, while in reality most weren't reviewed...
